/*
=============================================================
Create Database and Schemas
=============================================================
Script Purpose:
    This script creates a new database named 'b2b_source_db' after checking if it already exists. 
    If the database exists, it is dropped and recreated.
	
WARNING:
    Running this script will drop the entire 'b2b_source_db' database if it exists. 
    All data in the database will be permanently deleted. Proceed with caution 
    and ensure you have proper backups before running this script.


 B2B Data Platform - Source 1 (SQL Server)
-- Generated by Python, migrated via ELT pipeline to
-- PostgreSQL Staging.
--
-- ID strategy: all *_id columns are CHAR(32), matching
-- fake.uuid4().replace('-', '') from the Python generator.
-- IDs are assigned in Python, not by SQL Server- no IDENTITY.
--
-- Load order (must match Business Entity Dependency Levels):
--   Level 0: Companies, Categories
--   Level 1: Customers, Suppliers, Products
--   Level 2: Supplier_Product_Mapping
--   Level 3: Orders
--   Level 4: Order_Items
*/

USE master;
GO

-- Drop and recreate the 'b2b_source_db' database
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'b2b_source_db')
BEGIN
    ALTER DATABASE b2b_source_db SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE b2b_source_db;
END;
GO

-- Create the 'Source1' database
CREATE DATABASE b2b_source_db;
GO

USE b2b_source_db;
GO

-- Create Schemas
CREATE SCHEMA source;
GO

/*
-- Drop in reverse dependency order so re-running this script
during development doesn't hit FK errors.
*/
IF OBJECT_ID('source.Order_Items','U') IS NOT NULL DROP TABLE source.Order_Items;
IF OBJECT_ID('source.Orders','U') IS NOT NULL DROP TABLE source.Orders;
IF OBJECT_ID('source.Supplier_Product_Mapping','U') IS NOT NULL DROP TABLE source.Supplier_Product_Mapping;
IF OBJECT_ID('source.Products','U') IS NOT NULL DROP TABLE source.Products;
IF OBJECT_ID('source.Categories','U') IS NOT NULL DROP TABLE source.Categories;
IF OBJECT_ID('source.Suppliers','U') IS NOT NULL DROP TABLE source.Suppliers;
IF OBJECT_ID('source.Customers','U') IS NOT NULL DROP TABLE source.Customers;
IF OBJECT_ID('source.Companies','U') IS NOT NULL DROP TABLE source.Companies;
GO

 
-- ============================================================
-- Level 0: Root Entities (no dependencies) (Companies, Categories)
-- ============================================================

-- ============================================================
-- Companies
-- ============================================================

CREATE TABLE source.Companies (
    company_id      CHAR(32)      NOT NULL PRIMARY KEY,
    company_name    NVARCHAR(200) NOT NULL UNIQUE,
    company_type    NVARCHAR(20)  NOT NULL,
    cuit_tax_id     NVARCHAR(20)  NOT NULL UNIQUE,
    rating          DECIMAL(2,1)  NOT NULL,
    country         NVARCHAR(100) NOT NULL,
    city            NVARCHAR(100) NOT NULL,
    address         NVARCHAR(255) NOT NULL,
    created_at      DATETIME2     NOT NULL,
    updated_at      DATETIME2     NOT NULL,

	CONSTRAINT CK_Companies_type
		CHECK (company_type IN (
			'Buyer','Supplier')),

    CONSTRAINT CK_Companies_Rating
        CHECK (rating BETWEEN 1.0 AND 5.0),

    CONSTRAINT CK_Companies_UpdatedAfterCreated
        CHECK (updated_at >= created_at)
);
GO

-- ============================================================
-- Categories
-- ============================================================

CREATE TABLE source.Categories (
    category_id     CHAR(32)      NOT NULL PRIMARY KEY,
    category_name   NVARCHAR(150) NOT NULL UNIQUE,
    created_at      DATETIME2     NOT NULL,
    updated_at      DATETIME2     NOT NULL,

    CONSTRAINT CK_Categories_UpdatedAfterCreated
        CHECK (updated_at >= created_at)
);

GO

-- ========================================================================================================================
--											Level 1: Depend on Level 0
-- ========================================================================================================================
-- ============================================================
-- Customers (Dependent on Companies)
-- ============================================================
CREATE TABLE source.Customers (
    customer_id     CHAR(32)      NOT NULL PRIMARY KEY,
    company_id      CHAR(32)      NOT NULL,
    first_name      NVARCHAR(100) NOT NULL,
    last_name       NVARCHAR(100) NOT NULL,
    email           NVARCHAR(255) NOT NULL UNIQUE,
    phone_number           NVARCHAR(30)  NULL,
    gender          NVARCHAR(20)  NULL,
    date_of_birth   DATE          NULL,
    job_title       NVARCHAR(150) NULL,
    created_at      DATETIME2     NOT NULL,
    updated_at      DATETIME2     NOT NULL,

    CONSTRAINT FK_Customers_Companies
        FOREIGN KEY (company_id)
        REFERENCES source.Companies(company_id),

    CONSTRAINT CK_Customers_UpdatedAfterCreated
        CHECK (updated_at >= created_at),

	CONSTRAINT CK_Customers_Gender
		CHECK (gender IN ('Male','Female'))
);
GO


-- ============================================================
-- Suppliers
-- ============================================================

CREATE TABLE source.Suppliers (
    supplier_id     CHAR(32)      NOT NULL PRIMARY KEY,
    company_id      CHAR(32)      NOT NULL,
    supplier_name   NVARCHAR(200) NOT NULL,
    contact_name    NVARCHAR(150) NULL,
    email           NVARCHAR(255) NOT NULL UNIQUE,
    phone_number    NVARCHAR(30)  NULL,
    created_at      DATETIME2     NOT NULL, 
    updated_at      DATETIME2     NOT NULL,

    CONSTRAINT FK_Suppliers_Companies
        FOREIGN KEY (company_id)
        REFERENCES source.Companies(company_id),

    CONSTRAINT CK_Suppliers_UpdatedAfterCreated
        CHECK (updated_at >= created_at)
);
GO



-- ============================================================
-- Products (Dependent on Categories)
-- ============================================================

CREATE TABLE source.Products (
    product_id      CHAR(32)      NOT NULL PRIMARY KEY,
    sku             NVARCHAR(50)  NOT NULL UNIQUE,
    product_name    NVARCHAR(200) NOT NULL,
    category_id     CHAR(32)      NOT NULL,
    brand			NVARCHAR(100) NOT NULL,
	variant			NVARCHAR(50)  NOT NULL,
	cost_price      DECIMAL(12,2) NOT NULL,
	catalog_price   DECIMAL(12,2) NOT NULL,
    is_active       BIT           NOT NULL DEFAULT 1,
    created_at      DATETIME2     NOT NULL,
    updated_at      DATETIME2     NOT NULL,


    CONSTRAINT FK_Products_Categories
        FOREIGN KEY (category_id)
        REFERENCES source.Categories(category_id),

    CONSTRAINT CK_Products_Prices
        CHECK (
            catalog_price >= 0
            AND cost_price >= 0
            AND catalog_price >= cost_price
        ),

    CONSTRAINT CK_Products_UpdatedAfterCreated
        CHECK (updated_at >= created_at)
);

GO



-- ========================================================================================================================
--											Level 2 - Depends on Level 1 (Suppliers + Products)
-- ========================================================================================================================

-- ============================================================
---- Supplier Product Mapping (Dependent on Suppliers, Products)
-- ============================================================
CREATE TABLE source.Supplier_Product_Mapping (
    supplier_product_id   CHAR(32)      NOT NULL PRIMARY KEY,
    supplier_id           CHAR(32)      NOT NULL,
    product_id            CHAR(32)      NOT NULL,
    supplier_price        DECIMAL(12,2) NOT NULL,
    lead_time_days        INT           NOT NULL,
    is_preferred_supplier BIT           NOT NULL DEFAULT 0,
    created_at            DATETIME2     NOT NULL,
    updated_at            DATETIME2     NOT NULL ,

    CONSTRAINT FK_SPM_Suppliers
        FOREIGN KEY (supplier_id)
        REFERENCES source.Suppliers(supplier_id),

    CONSTRAINT FK_SPM_Products
        FOREIGN KEY (product_id)
        REFERENCES source.Products(product_id),

    CONSTRAINT CK_SPM_Price
        CHECK (supplier_price >= 0),

    CONSTRAINT CK_SPM_LeadTime
        CHECK (lead_time_days >= 0),

    CONSTRAINT CK_SPM_UpdatedAfterCreated
        CHECK (updated_at >= created_at),

		CONSTRAINT UQ_SPM_Supplier_Product
		UNIQUE (supplier_id, product_id)
);
GO


-- ========================================================================================================================
--												Level 3: Depends on Customers (Level 1)
-- Note: lead_id is NOT a foreign key - Marketing_Leads lives
-- only in PostgreSQL (Source 3, CSV-generated), never in
-- SQL Server. It's carried here as a plain reference value so
-- the pipeline can link Orders to Marketing_Leads later
-- downstream in Postgres.
-- ========================================================================================================================

-- ============================================================
-- Orders (Dependent on Companies, Customers)
-- ============================================================

CREATE TABLE source.Orders (
    order_id        CHAR(32)      NOT NULL PRIMARY KEY,
    customer_id     CHAR(32)      NOT NULL,
    company_id      CHAR(32)      NOT NULL,
    lead_id         CHAR(32)      NULL,		-- no FK: Marketing_Leads is a Postgres-only table
    order_date      DATETIME2     NOT NULL,
    order_status    NVARCHAR(20)  NOT NULL, -- expected: 'Confirmed'/ "Pending" / "Processing" / "Shipped" / "Delivered" / "Cancelled"
    payment_status  NVARCHAR(20)  NOT NULL,	-- expected: 'pending' / 'paid' / 'refunded' /'failed'
    order_total     DECIMAL(12,2) NOT NULL,	-- Rule 7: computed by generator as SUM(Order_Items.line_total)
    created_at      DATETIME2     NOT NULL,
    updated_at      DATETIME2     NOT NULL,

	CONSTRAINT CK_Order_Status
		CHECK (
		order_status IN ('Pending','Confirmed','Processing','Shipped','Delivered','Cancelled')
		),

	CONSTRAINT CK_Payment_Status
		CHECK (
			payment_status IN ('pending', 'paid','failed','refunded')
		),

    CONSTRAINT FK_Orders_Customers
        FOREIGN KEY (customer_id)
        REFERENCES source.Customers(customer_id),

    CONSTRAINT FK_Orders_Companies
        FOREIGN KEY (company_id)
        REFERENCES source.Companies(company_id),


    CONSTRAINT CK_Orders_Total
        CHECK (order_total >= 0),

    CONSTRAINT CK_Orders_UpdatedAfterCreated
        CHECK (updated_at >= created_at)

);
GO

-- ========================================================================================================================
--												Level 4: Depends on Orders (Level 3) + Supplier_Product_Mapping (Level 2)))
-- ========================================================================================================================

-- ============================================================
---- Level 4: Order Items (Dependent on Orders, Suppliers)
-- ============================================================
CREATE TABLE source.Order_Items (
    order_item_id       CHAR(32)      NOT NULL PRIMARY KEY,
    order_id            CHAR(32)      NOT NULL,
    supplier_product_id CHAR(32)      NOT NULL,
    quantity            INT           NOT NULL,
    unit_price          DECIMAL(12,2) NOT NULL,
    discount_amount     DECIMAL(12,2) NOT NULL DEFAULT 0,
    line_total          DECIMAL(12,2) NOT NULL,
    created_at          DATETIME2     NOT NULL,
    updated_at          DATETIME2     NOT NULL,

    CONSTRAINT FK_OrderItems_Orders
        FOREIGN KEY (order_id)
        REFERENCES source.Orders(order_id),

    CONSTRAINT FK_OrderItems_SPM
        FOREIGN KEY (supplier_product_id)
        REFERENCES source.Supplier_Product_Mapping(supplier_product_id),

    CONSTRAINT CK_OrderItems_Quantity
        CHECK (quantity > 0),

    CONSTRAINT CK_OrderItems_Prices
        CHECK (
            unit_price >= 0
            AND discount_amount >= 0
            AND line_total >= 0
        ),

    CONSTRAINT CK_OrderItems_UpdatedAfterCreated
        CHECK (updated_at >= created_at),

	CONSTRAINT UQ_Order_Product
	UNIQUE(order_id, supplier_product_id)
);

GO








